import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Anton } from "next/font/google";
import "./globals.css";
import Footer from "@/src/shared/ui/sections/footer/footer.section";
import MainLayout from "@/src/shared/ui/layouts/main.layout";
import { Main } from "next/document";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const anton = Anton({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${anton.variable}`}>
        <MainLayout>
          {children}</MainLayout>
      </body>
    </html>
  );
}
